name: CRA → Hostinger (auto deploy)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production   # <- usa os Environment secrets

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Validate required secrets
        run: |
          test -n "${{ secrets.FTP_HOST }}" || { echo "Missing secret: FTP_HOST"; exit 1; }
          test -n "${{ secrets.FTP_USER }}" || { echo "Missing secret: FTP_USER"; exit 1; }
          test -n "${{ secrets.FTP_PASS }}" || { echo "Missing secret: FTP_PASS"; exit 1; }

      - name: Ensure .htaccess in build
        run: |
          if [ -f public/.htaccess ]; then
            cp public/.htaccess build/.htaccess
          fi

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:   ${{ secrets.FTP_HOST }}   # ex.: 82.180.153.191 (sem "ftp://")
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          port: 21
          local-dir: build/
          server-dir: /public_html/
          dangerous-clean-slate: true
          timeout: 600
